language: python

python:
  - '3.7'

dist: xenial

env:
  global:
    - BUILD_ON_TRAVIS=true

install:
  - pip install pipenv
  - pipenv sync

script: 
  - python manage.py test
  - coverage run --source='.' manage.py test rsser

after_success:
  - coveralls
