language: python

python:
  - '3.7'

dist: xenial

env:
  global:
    - BUILD_ON_TRAVIS=true

install:
  - pip install pipenv
  - pipenv sync

script: 
  - python manage.py test

after_success: 
  - coveralls
