# Generated by Django 2.1.4 on 2019-01-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_hash', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('size', models.IntegerField()),
                ('added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('photo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='name_ru')),
                ('title_en', models.CharField(max_length=200, verbose_name='name_en')),
                ('description', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('image_path', models.URLField()),
                ('status', models.CharField(choices=[('new', 'New'), ('current', 'Current'), ('archive', 'Archive')], max_length=1)),
                ('hosts', models.ManyToManyField(related_name='programs', to='rsser.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('url', models.URLField(verbose_name='url')),
                ('logo', models.URLField()),
                ('programs_root', models.CharField(max_length=200, verbose_name='programs root')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='rsser.Station'),
        ),
        migrations.AddField(
            model_name='host',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='rsser.Station'),
        ),
    ]
