# Generated by Django 2.2.2 on 2019-07-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0003_station_short_latin_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['title_ru']},
        ),
    ]
