# Generated by Django 2.2.2 on 2019-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsser', '0004_auto_20190701_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('notify', models.BooleanField(default=False)),
            ],
        ),
    ]
